nodePool: &ingress_nodepool ingresspool

nginx-ingress:
  controller:
    kind: DaemonSet
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    service:
      type: ClusterIP
    nodeSelector:
      nodepool: *ingress_nodepool
