# nameOverride: ""
provider: entercloudsuite

# supported kubernetes versions: 1.15.11 and 1.16.4
version: 1.15.11

# use versionOverride just for upgrading the master
cluster:
  replicas: 3
  vcpu: 2
  ram: 4
  versionOverride: 1.15.11-220
  monitoring:
    enabled: true
    version: 1.0.0

nodepools:
  - name: pool1
    replicas: 1
    vcpu: 2
    ram: 2
    autoscaler:
      enabled: true
      max: 5
