apiVersion: core.automium.io/v1beta1
kind: Service
metadata:
  labels:
    app: kubernetes-cluster
    helm.sh/chart: {{ include "automium-cluster.chart" . }}
    app.kubernetes.io/component: {{ include "automium-cluster.name" . }}
    app.kubernetes.io/part-of: {{ include "automium-cluster.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "serviceName" . }}
spec:
  env:
  - name: kubeadm_custom
    value: |-
      kubeletExtraArgs:
        system-reserved: cpu=500m,memory=500Mi,ephemeral-storage=1Gi
        kube-reserved: cpu=500m,memory=500Mi,ephemeral-storage=1Gi
  {{- if eq .Values.cluster.monitoring.enabled false }}
  extra: []
  {{- else }}
  extra:
  - name: monitoring
    version: {{ .Values.cluster.monitoring.version }}
  {{- end }}
  replicas: {{ .Values.cluster.replicas }}
  {{- if eq .Values.provider "entercloudsuite" }}
  flavor: {{ include "ecsFlavor" .Values.cluster }}
  {{- else }}
  flavor: "not implemented"
  {{- end }}
  tags: []
  version: v{{ .Values.cluster.versionOverride | default (include "serviceVersion" .Values.version) }}
