---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: automium-logging-filebeat
  namespace: kube-system
  labels:
    k8s-app: automium-logging-filebeat
spec:
  selector:
    matchLabels:
      k8s-app: automium-logging-filebeat
  template:
    metadata:
      labels:
        k8s-app: automium-logging-filebeat
        releaseRevision: {{ .Release.Revision | quote }}
    spec:
      serviceAccountName: automium-logging-filebeat-sa
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.9.2
        args: ["-c", "/etc/filebeat/filebeat.yml", "-e"]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
        resources:
          limits:
            cpu: {{ .Values.filebeat.resources.limits.cpu }}
            memory: {{ .Values.filebeat.resources.limits.memory }}
          requests:
            cpu: {{ .Values.filebeat.resources.requests.cpu }}
            memory: {{ .Values.filebeat.resources.requests.memory }}
        volumeMounts:
        - name: config
          mountPath: "/etc/filebeat/filebeat.yml"
          subPath: filebeat.yml
          readOnly: true
        - name: config
          mountPath: /etc/filebeat/ILMTemplate.yaml
          subPath: ILMTemplate.yaml
          readOnly: true
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0640
          name: automium-logging-filebeat-config
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        hostPath:
          path: /var/log
      - name: data
        hostPath:
          path: /var/lib/automium/filebeat-data
          type: DirectoryOrCreate

