---
clusterName: ""
filebeat:
  resources:
    limits:
      cpu: 1000m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
esCluster:
  url: ""
  username: ""
  password: ""
  insecureTLS: false
  indexName: "automium-logging"
  ILMpolicy_name: automium
ilm:
  actions:
    rollover:
      maximumIndexSize: 50gb
      max_age: 60d
    delete:
      min_age: 60d
  

