---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "serviceName" . }}-ambassador-example
  labels:
    helm.sh/chart: {{ include "example.chart" . }}
    app.kubernetes.io/part-of: {{ include "example.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: consul_example_mapping
      prefix: /
      service: example
      resolver: consul-automium
      load_balancer: 
        policy: round_robin
spec:
  ports:
  - name: http
    port: 8080