apiVersion: v1
kind: ConfigMap
metadata:
  name: automium-prometheus-config
  namespace: {{ .Release.Namespace }}
data:
  rules: |-
    groups:
    - name: etcd
      rules:
      - alert: HighLeaderChanges 
        expr: increase(etcd_server_leader_changes_seen_total[1h]) > 3
        for: 3m
        labels:
          severity: warning
        annotatations:
          summary: A high number of leader changes within the etcd cluster are happening
      - alert: NoLeader
        expr: etcd_server_has_leader != 1
        for: 3m
        labels:
          severity: critical
        annotatations:
          summary: Etcd member has no leader
    - name: node
      rules:
      - alert: HighCPULoad 
        expr: ( sum(node_load1) by (instance) / count(node_cpu_seconds_total{mode='system'}) by (instance) * 100 ) > 100
        for: 3h
        labels:
          severity: warning
        annotatations:
          summary: High CPU usage on node
      - alert: HighMemoryUsage
        expr: ( 1 - sum(node_memory_MemAvailable_bytes) by (instance) / sum(node_memory_MemTotal_bytes) by (instance) ) >= 80
        for: 3h
        labels:
          severity: warning
        annotatations:
          summary: High memory usage on node
      - alert: PodEvictionIn24h
        expr: ( predict_linear(node_filesystem_avail_bytes{mountpoint='/'}[1h], 24 * 3600) and ( 100 - ((node_filesystem_avail_bytes{mountpoint='/',fstype!='rootfs'} * 100) / node_filesystem_size_bytes{mountpoint='/',fstype!='rootfs'}) > 85) ) < 0
        for: 3h
        labels:
          severity: warning
        annotatations:
          summary: Node will evict pods in the next 24 hours
      - alert: CriticalLowDiskSpace
        expr: ( node_filesystem_avail_bytes{mountpoint='/'} / node_filesystem_size_bytes{mountpoint='/'} * 100 ) < 5
        for: 5m
        labels:
          severity: critical
        annotatations:
          summary: Node free space on root filesystem is critically low - pods may be have evicted
    - name: automium
      rules:
      - alert: PendingPods 
        expr: ( kube_pod_status_phase{phase='Pending'} ) > 0
        for: 10m
        labels:
          severity: warning
        annotatations:
          summary: Cluster has pending pods for too long
      - alert: UnschedulablePods 
        expr: cluster_autoscaler_unschedulable_pods_count > 0
        for: 20m
        labels:
          severity: critical
        annotatations:
          summary: Cluster has unschedulable pods for too long