---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: etcd-server
  name: etcd-k8s-svc
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    component: etcd
    tier: control-plane

