apiVersion: v1
kind: Secret
metadata:
  name: automium-grafana-datasources
  namespace: {{ .Release.Namespace }}
  labels:
     grafana_datasource: "true"
type: Opaque
stringData:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: "automium-monitoring-prometheus"
      type: prometheus
      access: proxy
      url: "http://{{ .Release.Name }}-prometheus-server"
      isDefault: true
      editable: false
   
