---
# Automium ###
automium:
  storageClass:
    provisioner: "kubernetes.io/cinder"
# Prometheus ###
prometheus:
  podSecurityPolicy:
    enabled: true
  alertmanager: 
    enabled: false
  nodeExporter:
    enabled: true
    tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
  pushgateway: 
    enabled: false
  kube-state-metrics:
    enabled: true
    nodeSelector:
      node-role.kubernetes.io/master: ""
    tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
  rbac: 
    namespaced: true
  configmapReload:
    prometheus:
      extraVolumeDirs:
      - /etc/config/automium
      extraConfigmapMounts:
      - name: automium-prometheus-config
        configMap: automium-prometheus-config
        mountPath: /etc/config/automium
  server: 
    ingress: 
      enabled: false
    service: 
      type: "NodePort"
      nodePort: "30001"
    persistentVolume: 
      enabled: true
      size: "50Gi"
    extraConfigmapMounts:
    - name: automium-prometheus-config
      configMap: automium-prometheus-config
      mountPath: /etc/prometheus/automium
    extraSecretMounts:
    - name: etcd-certs
      secretName: etcd-certs
      mountPath: /etc/prometheus/certs
    retention: 120h
    nodeSelector:
      node-role.kubernetes.io/master: ""
    tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    strategy:
      type: Recreate
    resources:
      requests:
        cpu: 0.5
        memory: 128Mi
      limits:
        cpu: 2
        memory: 2Gi
  serverFiles: 
    prometheus.yml:
      rule_files:
        - /etc/prometheus/automium/rules
      alerting:
        alertmanagers:
        - scheme: https
          path_prefix: /
          static_configs:
            - targets: []
  extraScrapeConfigs: |-
    - job_name: etcd-metrics
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - kube-system
      scheme: https
      tls_config:
        ca_file: /etc/prometheus/certs/ca.crt
        cert_file: /etc/prometheus/certs/prometheus.pem
        key_file: /etc/prometheus/certs/prometheus_key.pem
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
      - source_labels: ["__meta_kubernetes_service_label_k8s_app"]
        regex: etcd-server
        replacement: $1
        action: keep
      - source_labels: ["__meta_kubernetes_pod_host_ip"]
        target_label: host_ip
        action: replace
        regex: (.+)
        replacement: $1
      - source_labels: ["__meta_kubernetes_pod_node_name"]
        target_label: node
        action: replace
        regex: (.+)
        replacement: $1
# Grafana ###
grafana:
  enabled: true
  adminUser: "admin"
  persistence: 
    enabled: true
    size: "1Gi"
  ingress: 
    enabled: false
  service: 
    type: "NodePort"
    nodePort: "30000"
  sidecar:
    datasources:
      enabled: true
    dashboards: 
      enabled: true
  nodeSelector:
    node-role.kubernetes.io/master: ""
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
  deploymentStrategy:
    type: Recreate
