---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-default-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: nginx-ingress-default-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-ingress-default-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-ingress-default-backend
    spec:
      containers:
        - name: default-backend
          image: gcr.io/google_containers/defaultbackend:1.0
          securityContext:
            runAsUser: 65534
          ports:
          - containerPort: 8080
      {{ if .Values.nodePool }}
      nodeSelector:
        nodepool: {{ .Values.nodePool }}
      {{ end }}
---

apiVersion: v1
kind: Service
metadata:
  name: default-backend-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: nginx-ingress-default-backend
---
